const Colors = {
    PRIMARY_COLOR: '#000000',
    SECONDARY_TEXT_COLOR: '#686868',
    DISABLED_TEXT_COLOR: '#B3B3B3',
    LECTURE_CONTENT_PART_COLOR: '#F5F5F5',
    ACCENT_COLOR: '#8B15FF',
    ACCENT_COLOR_LIGHT: '#E6D2FF',
    TEXT_WHITE_COLOR: '#FFFFFF',
    TEXT_ERROR_COLOR: '#DC3545',
    SIDEBAR_COLOR: '#170833',
    CONTENT_HOVER_COLOR: '#DAE6FA',
    LINK_COLOR: '#007BFF',
    // Additional colors for issue report components
    BACKGROUND_COLOR: '#FFFFFF',
    BORDER_COLOR: '#E1E5E9',
    TEXT_TERTIARY_COLOR: '#9CA3AF',
    SUCCESS_COLOR: '#28A745',
    WARNING_COLOR: '#FFC107',

    GREEN_COLOR: '#28A745',
    GREEN_COLOR_LIGHT: '#05966920',
    
    PERCENTAGE_LOW_COLOR: '#DC3545',
    PERCENTAGE_MEDIUM_COLOR: '#FFC107',
    PERCENTAGE_HIGH_COLOR: '#28A745',
};

export default Colors;