const Colors = {
    PRIMARY_COLOR: '#000000',
    SECONDARY_TEXT_COLOR: '#686868',
    DISABLED_TEXT_COLOR: '#B3B3B3',
    LECTURE_CONTENT_PART_COLOR: '#F5F5F5',
    ACCENT_COLOR: '#8B15FF',
    TEXT_WHITE_COLOR: '#FFFFFF',
    TEXT_ERROR_COLOR: '#DC3545',
    SIDEBAR_COLOR: '#170833',
    CONTENT_HOVER_COLOR: '#DAE6FA',
};

export default Colors;